config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :travels
  resource :session

  root "travels#index"

  resources :travels, only: [ :index, :show ] do
    resources :comments, only: [ :create, :edit, :update, :destroy ]

    member do
      post :upload_images
    end
  end

  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true
  validate :start_date_before_end_date

  default_scope { order(created_at: :desc) }
  scope :for_user, ->(user) { where(user: user) }

  def dates_traveled
    start_date_str = start_date.present? ? start_date.strftime("%b %d, %Y") : nil
    end_date_str = end_date.present? ? end_date.strftime("%b %d, %Y") : nil

    if start_date_str.nil? && end_date_str.nil?
      "Not Provided"
    elsif start_date_str.nil?
      end_date_str
    elsif end_date_str.nil?
      start_date_str
    else
      "#{start_date_str} - #{end_date_str}"
    end
  end

  private

  def start_date_before_end_date
    if start_date.present? && end_date.present? && start_date >= end_date
      errors.add(:start_date, "must be before the end date")
    end
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  include UserScopedResources

  before_action :set_travel, only: [ :show, :edit, :update, :destroy, :upload_images ]
  before_action :authenticate_user!
  before_action lambda {
    resize_before_save(travel_params[:images], 300, 300)
  }, only: %i[create upload_images]

  def index
    @travels = if params[:scope] == "explore"
                 policy_scope(Travel.where.not(user: current_user))
    else
                 policy_scope(current_user.travels)
    end
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    authorize @travel
    @images = @travel.images.order(created_at: :desc)
  end

  def new
    @travel = Travel.new
    authorize @travel
  end

  def edit
    authorize @travel
  end

  def create
    @travel = Travel.new(travel_params.except(:images).merge(user: current_user))
    authorize @travel

    respond_to do |format|
      if @travel.save
        attach_images(@travel)
        format.html { redirect_to @travel, notice: "#{@travel.name} was successfully created." }
        format.json { render :show, status: :created, location: @travel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @travel

    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: "#{@travel.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @travel
    @travel.destroy!

    respond_to do |format|
      format.html do
        redirect_to travels_path, notice: "#{@travel.name} was successfully destroyed."
      end
      format.turbo_stream do
        @travels = policy_scope(Travel.where(user: current_user))
        render "travels/index"
      end
    end
  end

  def upload_images
    authorize @travel

    if params[:travel][:images].present?
      attach_images(@travel)
      @images = @travel.images.order(created_at: :desc)
      respond_to do |format|
        format.html { redirect_to @travel, notice: "Images were successfully uploaded." }
        format.turbo_stream
      end
    else
      redirect_to @travel, alert: "No images selected for upload."
    end
  end

  private

  def set_travel
    if %w[show edit update destroy upload_images].include?(action_name)
      @travel = Travel.find(params[:id])
    else
      @travel = user_scoped(Travel).find(params[:id])
    end
  end

  def travel_params
    params.require(:travel).permit(:name, :start_date, :end_date, :favorite, images: [])
  end

  def attach_images(travel)
    if params[:travel][:images].present?
      params[:travel][:images].each do |image|
        travel.images.attach(image)
      end
    end
  end

  def resize_before_save(image_params, width, height)
    return unless image_params.present?
    image_params.each do |image_param|
      begin
        ImageProcessing::MiniMagick
          .source(image_param)
          .resize_to_fit(width, height)
          .call(destination: image_param.tempfile.path)
      rescue StandardError => e
        Rails.logger.error "Image resizing failed: #{e.message}"
      end
    end
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_create_form.html.erb
<%= form_with(model: @travel, local: true, html: { multipart: true }) do |form| %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "rounded-md px-3.5 py-2.5 border border-gray-300 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "rounded-md px-3.5 py-2.5 border border-gray-300 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "rounded-md px-3.5 py-2.5 border border-gray-300 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :favorite %>
    <%= form.check_box :favorite, class: "rounded-md px-3.5 py-2.5 border border-gray-300" %>
  </div>
  <div class="my-5">
    <%= form.label :images, "Add Images" %>
    <%= form.file_field :images, multiple: true, accept: 'image/png, image/gif, image/jpeg', data: { image_upload_target: "input", action: "change->image-upload#toggleButton" } %>
  </div>
  <div>
    <%= form.submit "Create Travel", class: "btn-primary" %>
  </div>
<% end %>

app/views/travels/_form.html.erb
<%= form_with(model: travel, class: "contents") do |form| %>
  <% if travel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul class="list-disc ml-6">
        <% travel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": travel.errors[:name].none?, "border-red-400 focus:outline-red-600": travel.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": travel.errors[:start_date].none?, "border-red-400 focus:outline-red-600": travel.errors[:start_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": travel.errors[:end_date].none?, "border-red-400 focus:outline-red-600": travel.errors[:end_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :favorite %>
    <%= form.checkbox :favorite, class: ["block shadow rounded-md border outline-none mt-2 h-5 w-5", {"border-gray-400 focus:outline-blue-600": travel.errors[:favorite].none?, "border-red-400 focus:outline-red-600": travel.errors[:favorite].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn-primary" %>
  </div>
<% end %>

app/views/travels/_image_form.html.erb
<div id="image_upload_form">
  <%= form_with(model: @travel, url: upload_images_travel_path(@travel), method: :post, local: true, html: { multipart: true, data: { controller: "image-upload", action: "turbo:submit-end->image-upload#clearInput" } }, class: "flex flex-col") do |form| %>
    <div class="my-5">
      <%= form.label :images, "Add Images", class: "subheading" %>
      <%= form.file_field :images, multiple: true, accept: 'image/png, image/gif, image/jpeg', data: { image_upload_target: "input", action: "change->image-upload#toggleButton" },class: "mt-2" %>
    </div>
    <div>
      <div class="flex">
          <%= form.submit "Upload", class: "btn-primary ml-auto", data: { image_upload_target: "button" }, disabled: true %>
      </div>
    </div>
  <% end %>
</div>

app/views/travels/_images.html.erb
<div id="images_list">
  <% if images.present? && images.any? %>
    <div class="images flex flex-wrap -m-2">
      <% images.each do |image| %>
        <div class="p-2 w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/6">
          <%= image_tag image, alt: "#{travel.name} image", class: "travel-image w-full h-auto rounded-lg shadow-md" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No images available</p>
  <% end %>
</div>

app/views/travels/_travel.html.erb
<div id="<%= dom_id travel %>" class="relative">
  <%= link_to travel_path(travel), data: { turbo_frame: "_top" } do %>
    <%= render partial: "travels/travel_card_content", locals: { travel: travel } %>
  <% end %>
</div>

app/views/travels/_travel_card_content.html.erb
<div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow-md md:flex-row hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mb-6">
  <div class="relative">
    <% if travel.images.attached? %>
      <%= image_tag travel.images.first, alt: "#{travel.name} thumbnail", class: "object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" %>
    <% else %>
      <div class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg">
          <%= image_tag "no_image_available.jpg", alt: "No Image Placeholder" %>
      </div>
    <% end %>
    <% if travel.favorite %>
        <%= heroicon "heart", options: { class: "absolute top-4 right-4 text-pink-400 h-6 w-6" } %>
      <% else %>
        <%= heroicon "heart", variant: :outline, options: { class: "absolute top-2 right-2 text-white h-6 w-6" } %>
      <% end %>
  </div>
  <div class="flex flex-col justify-between p-4 leading-normal">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
      <%= travel.name %>
    </h5>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400 flex flex-nowrap">
      <strong class="block font-medium mb-1">Dates Visited:</strong>
      <%= travel.dates_traveled %>
    </p>
  </div>
</div>

app/views/travels/edit.html.erb
<% content_for :title, "Editing travel" %>

<div class="md:w-2/3 w-full">
  <div class="flex justify-between items-center mb-4">
    <h1 class="heading mb-4">Editing travel</h1>
    <%= link_to "Back to travels", travels_path, class: "btn-secondary" %>
  </div>


  <%= render "form", travel: @travel %>

  <%= link_to "Show this travel", @travel, class: "btn-secondary" %>
</div>

app/views/travels/index.html.erb
<% content_for :title, "Travels" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="heading mb-2">Travels</h1>
    <%= link_to "New travel", new_travel_path, class: "btn-primary" %>
  </div>

  <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
    <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-styled-tab" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-indigo-600 hover:text-indigo-600 dark:text-indigo-500 dark:hover:text-indigo-500 border-indigo-600 dark:border-indigo-500" data-tabs-inactive-classes="dark:border-transparent text-gray-500 hover:text-gray-600 dark:text-gray-400 border-gray-100 hover:border-gray-300 dark:border-gray-700 dark:hover:text-gray-300" role="tablist">
      <li class="me-2" role="presentation">
        <%= link_to 'My Travels', travels_path(scope: 'my_travels'), class: "font-medium text-xl inline-block p-4 border-b-2 rounded-t-lg #{'text-indigo-600 border-indigo-600' if params[:scope] != 'explore'}" %>
      </li>
      <li class="me-2" role="presentation">
        <%= link_to 'Explore', travels_path(scope: 'explore'), class: "font-medium text-xl inline-block p-4 border-b-2 rounded-t-lg #{'text-indigo-600 border-indigo-600' if params[:scope] == 'explore'}" %>
      </li>
    </ul>
  </div>

  <%= turbo_frame_tag "travels" do %>
    <div id="travels" class="min-w-full">
      <% if @travels.any? %>
        <%= render partial: "travels/travel", collection: @travels %>
      <% else %>
        <p class="text-center my-10">No travels found.</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/travels/index.turbo_stream.erb
<%= turbo_stream.replace "travels" do %>
  <div id="travels" class="min-w-full">
    <% if @travels.any? %>
      <% @travels.each do |travel| %>
        <%= render partial: "travel", locals: { travel: travel } %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No travels found.</p>
    <% end %>
  </div>
<% end %>
<%= turbo_stream.append "flash", partial: "layouts/flash", locals: { notice: "#{@travel.name} was successfully destroyed." } %>

app/views/travels/new.html.erb
<h1 class="font-bold text-4xl mb-4">New Travel</h1>
<%= render partial: "create_form" %>

app/views/travels/show.html.erb
<div class="w-full">
  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold heading">Viewing Travel: <%= @travel.name %></h1>
    <%= link_to "Back to travels", travels_path, class: "btn-secondary" %>
  </div>

  <div id="<%= dom_id @travel %>" class="relative">
    <%= render partial: "travels/travel_card_content", locals: { travel: @travel } %>
  </div>

  <% if @travel.user == current_user %>
    <div class="w-1/2 mb-6">
      <%= render partial: "image_form" %>
    </div>
  <% end %>

  <h2 class="subheading mt-5">Images</h2>
  <%= turbo_frame_tag "images" do %>
    <%= render partial: "travels/images", locals: { images: @images, travel: @travel } %>
  <% end %>


  <h2 class="subheading mt-5">Add a new Comment</h2>
  <div class="w-1/2 mb-6">
    <%= turbo_frame_tag "new_comment" do %>
      <%= render partial: "comments/form", locals: { comment: Comment.new, commentable: @travel } %>
    <% end %>
  </div>

  <h2 class="subheading mt-5">Comments</h2>
  <%= turbo_frame_tag "comments" do %>
    <% @travel.comments.each do |comment| %>
      <%= render partial: "comments/comment", locals: { comment: comment } %>
    <% end %>
  <% end %>


  <% if @travel.user == current_user %>
    <div class="inline-block ml-2 flex justify-end mt-8 pb-4">
      <%= link_to "Edit this travel", edit_travel_path(@travel), class: "btn-primary mr-4" %>
      <%= button_to "Destroy this travel", @travel, method: :delete, data: { turbo: false, confirm: "Are you sure?" }, class: "btn-danger" %>
    </div>
  <% end %>
</div>

app/views/travels/upload_images.turbo_stream.erb
<%= turbo_stream.replace "images_list" do %>
  <%= render partial: "travels/images", locals: { images: @images, travel: @travel } %>
<% end %>

<%= turbo_stream.replace "image_upload_form" do %>
  <%= render partial: "image_form", locals: { travel: @travel } %>
<% end %>